server:
  port: 80
  servlet:
    context-path: /BookPage
spring:
  datasource:
    password: admin123
    url: jdbc:mysql://localhost:3306/bookproject_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  main:
    allow-circular-references: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 933680659275-g923u6uosspurhic0o4etk75g05uei4m.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile